### ISSUE TITLE
Changes in .cljc files not picked up on phoenix/reload!

### ISSUE THREAD

**Issue by whodidthis** [james-henderson/phoenix#11]
Testable by changing phoenix-api template's handler.clj to .cljc.

As a temporary workaround need to reload the namespace and then phoenix/reload!

**Comment by jarohen** [comment]
Hi @whodidthis, thanks for letting me know!

Phoenix's support for reloading namespaces comes straight from clojure.tools.namespace - will check to see if they have updated as a result of the new file extensions.

James

**Comment by jarohen** [comment]
Hi there - I've bumped the version, made the necessary changes, and released 0.1.2-SNAPSHOT - could you let me know whether this works for you?

James

**Comment by whodidthis** [comment]
Might be a bug in tools.namespace http://dev.clojure.org/jira/browse/TNS-34

**Comment by whodidthis** [comment]
Ticket looks to be resolved in `org.clojure/tools.namespace "0.2.11"`.

**Comment by jarohen** [comment]
Thanks, will get an updated version deployed when I get a moment :)

**Comment by jarohen** [comment]
Have pushed 0.1.3-SNAPSHOT with this version bump. There's quite a few changes on the 0.2.0-branch so won't push this as yet - one for this weekend, I hope :)
