### ISSUE TITLE
prismatic/schema incompatibility?

### ISSUE THREAD

**Issue by whodidthis** [james-henderson/phoenix#8]
For some mysterious reasons when trying to use `schema.core/fn` with phoenix I get 

```
#<CompilerException java.lang.RuntimeException: No such var: schema.core/fn
```

Not sure how this is possible and hopefully i didn't try anything stoopid but I tried `lein new phoenix-api` and then changed the single usage of `fn` to use `schema.core/fn`:
https://github.com/whodidthis/phoenix-api-schema/blob/master/src/phoenix_api_schema/handler.clj#L16

`lein repl` works fine, when trying `(phoenix/start!)` the runtimeexception happens

**Comment by jarohen** [comment]
Hi - can't see anything stoopid straightaway, must be both of us!

Have managed to reproduce this in a new project, will investigate.

Thanks for letting me know :)

James

**Comment by jarohen** [comment]
Looks like this is a problem with Phoenix AOT'ing phoenix.main when it's built - this in turn AOT compiles schema. 

Will see what can be done to remove this AOT requirement!

**Comment by whodidthis** [comment]
Good thing it was reproducable, noticed it after trying phoenix on my own stuff. I also tried schema on a juxt/modular template before creating this issue just in case hehe.

I like the idea of combining configuration with components since configuration is often needed on them.

**Comment by jarohen** [comment]
Hi again - have released 0.1.1-SNAPSHOT with a fix for this issue - could you give it a try?

The problem was that `phoenix.main` transitively required `schema.core`, so the Clojure compiler AOT compiled the latter when I asked it to AOT compile the former. It's not a pretty fix, but if you make the requires at runtime, rather than in the `ns`, it only AOT compiles that particular file:

``` clojure
(defn -main []
  ;; This is split out because we don't want Phoenix and its
  ;; transitive dependencies AOT-compiled with this namespace. See #8

  (require '[phoenix]
           '[phoenix.jar])

  (eval
   `(let [project# {:phoenix/config (phoenix-config-location)
                    :repl-options (repl-options)}]

      (alter-var-root #'phoenix.jar/built? (constantly true))

      (phoenix/init-phoenix! (io/resource (phoenix-config-location)))

      (phoenix/init-nrepl! project#)

      (#'phoenix/do-start!))))
```

Not pretty, but it's quite contained, and seems to work!

James

**Comment by jarohen** [comment]
Also, having some issues with Clojars at the moment - it's returning 400s when I try `lein deploy` - could you let me know if you have trouble getting hold of the SNAPSHOT?

Cheers :)

**Comment by whodidthis** [comment]
Does work with 0.1.1-SNAPSHOT!

**Comment by jarohen** [comment]
Great :) Thanks - I've just pushed 0.1.1, with this fix.

Cheers,

James
